//Dashboard Boxes

export const GET_DASHBOARD_DATA_ALL_ATTEMPT = "GET_DASHBOARD_DATA_ALL_ATTEMPT";
export const GET_DASHBOARD_DATA_ALL_SUCCESS = "GET_DASHBOARD_DATA_ALL_SUCCESS";
export const GET_DASHBOARD_DATA_ALL_FAIL = "GET_DASHBOARD_DATA_ALL_FAIL";
